import '../styles/globals.css';
import Header from 'components/common/header';
import Footer from 'components/common/footer';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { useEffect, useState } from 'react';
import { faLongArrowUp, faPhone } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Image from 'next/image';
import Script from 'next/script';
import Head from 'next/head';
import Link from 'next/link';
// Swiper
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/autoplay';
import 'swiper/css/effect-cube';
import 'swiper/css/thumbs';
import 'swiper/css/effect-cards';
import 'react-image-gallery/styles/css/image-gallery.css';

//Animation on scrolling
import 'animate.css';
config.autoAddCss = false;

function MyApp({ Component, pageProps, router }) {
    // Set toggle for button scroll to top

    const [isVisible, setIsVisible] = useState(false);
    const toggleVisibility = () => {
        if (window.pageYOffset > 300) {
            setIsVisible(true);
        } else {
            setIsVisible(false);
        }
    };
    const scrollToTop = () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth',
        });
    };
    useEffect(() => {
        window.addEventListener('scroll', toggleVisibility);

        return () => {
            window.removeEventListener('scroll', toggleVisibility);
        };
    }, []);
    return (
        <>
            {/* begin::ScrollToTop */}
            <button
                className={`bg-primary-color w-12 h-12 rounded-full flex justify-center 
          items-center fixed bottom-14 right-1 z-10 ${
              isVisible ? 'opacity-100' : 'opacity-0'
          }`}
                onClick={() => scrollToTop()}
            >
                <FontAwesomeIcon icon={faLongArrowUp} color='white' size='2x' />
            </button>
            {/* end::ScrollToTop */}
            {/* begin::SocialMediaButton */}
            <div className='fixed w-9 h-w-9 bottom-9 left-8 z-10'>
                <Image
                    src={'/youtube.png'}
                    alt='zalo icon'
                    width={32}
                    height={32}
                />
            </div>
            <div className='fixed w-9 h-w-9 bottom-9 left-8  translate-x-full z-10'>
                <Image
                    src={'/facebooks.png'}
                    alt='zalo icon'
                    width={32}
                    height={32}
                />
            </div>

            {/*  end:::SocialMediaButton*/}
            {/*  begin::phone button */}
            <Link href='tel:0962116789' passHref>
                <div className='phone-wrapper fixed top-28 left-16 z-50'>
                    <div className='flex justify-center items-center'>
                        <div className='z-50 absolute  bg-[#9BF080] p-3 rounded-full animate-pulse'>
                            <FontAwesomeIcon
                                icon={faPhone}
                                color='#fff'
                                size='2x'
                            />
                        </div>
                        <div className='h-12 w-12 rounded-full absolute animate-scaling'></div>
                        <div className='h-12 w-12 rounded-full absolute animate-[scaling_2s_linear_infinite_1s]'></div>
                    </div>
                </div>
            </Link>
            {/*  end::phone button */}
            {/* begin::ZaloButton */}
            <div
                className='zalo-chat-widget'
                data-oaid='3764014308364109214'
                data-welcome-message='Rất vui khi được hỗ trợ bạn!'
                data-autopopup='3s'
                data-width=''
                data-height=''
            ></div>
            {/* end::ZaloButton */}

            <Head>
                <title>Nhà gỗ Ba miền</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link
                    rel='icon'
                    type='image/jpg'
                    sizes='64x64'
                    href='/logo_ng3m.jpg'
                />
            </Head>
            <Header />
            <Component {...pageProps} router={router} />
            <Script defer src='https://sp.zalo.me/plugins/sdk.js'></Script>
            <Footer />
        </>
    );
}

export default MyApp;

