import {useState, useEffect} from "react";
import GridLayoutMauNha from "components/common/gridLayoutMauNha";
import Posts from "components/home/Posts";
import Services from "components/home/Services";
import Head from "next/head";
import Image from "next/image";
import About from "components/home/About";
import {Swiper, SwiperSlide} from "swiper/react";
import {Navigation, Pagination, Autoplay} from "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/autoplay";
import Commit from "components/home/Commit";
import {faLongArrowUp, faFaceAngry} from "@fortawesome/free-solid-svg-icons";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";

const images = ["/banner1.jpg", "/banner2.jpg", "/banner3.jpg"];

export default function Home() {
  // Set toggle for button scroll to top
  const [isVisible, setIsVisible] = useState(false);
  const toggleVisibility = () => {
    if (window.pageYOffset > 300) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };
  useEffect(() => {
    window.addEventListener("scroll", toggleVisibility);

    return () => {
      window.removeEventListener("scroll", toggleVisibility);
    };
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button
          className={`bg-primary-color w-14 h-14 rounded-full flex justify-center 
          items-center fixed bottom-9 right-8 z-10 ${
            isVisible ? "opacity-100" : "opacity-0"
          }`}
          onClick={() => scrollToTop()}
        >
          <FontAwesomeIcon icon={faLongArrowUp} color="white" size="2x" />
        </button>
        {/* Social media button */}
        <div className="fixed bg-[#3B5998] w-12 h-12 bottom-9 left-8 z-10">
          <FontAwesomeIcon icon={faFaceAngry} />
        </div>
        <div className="fixed bg-[#bb0000] w-12 h-12 bottom-9 left-8  translate-x-full z-10">
          <FontAwesomeIcon icon={faFaceAngry} />
        </div>
        <div
          className="fixed bg-[#00aff0] w-12 h-12 bottom-9 left-8 z-10"
          style={{transform: "translateX(200%)"}}
        >
          <FontAwesomeIcon icon={faFaceAngry} />
        </div>
        <Swiper
          modules={[Navigation, Pagination, Autoplay]}
          slidesPerView={1}
          navigation
          autoplay={{delay: 3000}}
          loop={true}
          pagination={{clickable: true}}
          onSlideChange={() => console.log("slide change")}
        >
          {images &&
            images.map((value, index) => (
              <SwiperSlide key={index}>
                <div className="w-full h-[460px]">
                  <Image src={value} alt="banner 1" layout="fill" />
                </div>
              </SwiperSlide>
            ))}
        </Swiper>
        <About />
        <div className="mb-5">
          <GridLayoutMauNha />
        </div>
        <div className="flex justify-start container mb-10">
          <Services />
          <Posts />
        </div>
        <div>
          <Commit />
        </div>
      </main>
    </div>
  );
}
