import Head from "next/head";
import Image from "next/image";
import Banner from "components/home/Banner";
import About from "components/home/About";
import styles from "../styles/Home.module.css";

const images = [
  "/banner1.jpg",
  "/banner2.jpg",
  "/banner3.jpg",
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner images={images} height="475px" isControl />
        <About />
      </main>
    </div>
  );
}
